### ISSUE TITLE
Seems to be an issue with selecting the environment

### ISSUE THREAD

**Issue by ghoul-keeper** [solserer-labs/candy.signer#1]
Hi there! I'm just reading the code to make sure it does what we want it. It looks like the connection string is hardcoded even though you have a drop down to select mainnet or devnet. I don't see anywhere where that gets updated.

I can try and get a PR up for you and test it out though to see if it works as expected. Please correct me if I'm wrong though. I'm still reading through and I haven't personally tested it yet.

https://github.com/solserer-labs/candy.signer/blob/main/src/Home.tsx#L28

**Comment by solserer-labs** [comment]
good find ! should be fixed now

**Comment by ghoul-keeper** [comment]
Can confirm! Fixed!! Let's gooooooo!!! 
![image](https://user-images.githubusercontent.com/91776622/138153431-dca08a6f-ec1d-41fc-8dab-4392eeace039.png)
